import { Employee } from './employee';

export const EMPLOYEES: Employee[] = [
    {
        id: 0,
        nameFirst: 'John',
        nameLast: 'Smith',
        role: 'Dev',
        bio: 'bio goes here',
        email: 'email@email.com',
        phone: '323.323.3223',
        twitter: 'http://twitter.com',
        facebook: 'http://facebook.com',
        instagram: 'http://instagram.com',
    },
    {
        id: 1,
        nameFirst: 'Jane',
        nameLast: 'Smith',
        role: 'Dev',
        bio: 'bio goes here',
        email: 'email@email.com',
        phone: '323.323.3223',
        twitter: 'http://twitter.com',
        facebook: 'http://facebook.com',
        instagram: 'http://instagram.com',
    },
    {
        id: 2,
        nameFirst: 'John',
        nameLast: 'Smith',
        role: 'Dev',
        bio: 'bio goes here',
        email: 'email@email.com',
        phone: '323.323.3223',
        twitter: 'http://twitter.com',
        facebook: 'http://facebook.com',
        instagram: 'http://instagram.com',
    },
    {
        id: 3,
        nameFirst: 'Jane',
        nameLast: 'Smith',
        role: 'Dev',
        bio: 'bio goes here',
        email: 'email@email.com',
        phone: '323.323.3223',
        twitter: 'http://twitter.com',
        facebook: 'http://facebook.com',
        instagram: 'http://instagram.com',
    },
];
