import { Client } from './client';

export const CLIENTS: Client[] = [
    {
        id: 0,
        company: 'abc',
        contact: 'Steve',
        phone: '424.424.4224',
        street1: '123 Main St',
        street2: '#3245',
        city: 'Los Angeles',
        state: 'CA',
        zip: 90000,
        emailPrimary: 'client@client.com',
        emailSecondary: 'client2@client.com',
        site1: 'http://clientsite.com',
        site2: 'http://clientsite2.com',
        site3: '',
        facebook: 'http://facebook.com',
        twitter: 'http://twitter.com',
        instagram: 'http://instagram.com',
        logoWhite: './assets/logoWhite.png',
        logoBlack: './assets/logoBlack.png',
    },
    {
        id: 1,
        company: 'acme',
        contact: 'Lara',
        phone: '424.424.4224',
        street1: '123 Main St',
        street2: '#3245',
        city: 'Los Angeles',
        state: 'CA',
        zip: 90000,
        emailPrimary: 'client@client.com',
        emailSecondary: 'client2@client.com',
        site1: 'http://clientsite.com',
        site2: 'http://clientsite2.com',
        site3: '',
        facebook: 'http://facebook.com',
        twitter: 'http://twitter.com',
        instagram: 'http://instagram.com',
        logoWhite: './assets/logoWhite.png',
        logoBlack: './assets/logoBlack.png',
    },
];

